create schema sublanguages;
-- This is a line comment
-- ctr+/

/*This is a block comment
 * 
 * ctr+shift+/
 * 
 * If you are in VS Code and want to do a similar short cut for a block comment that would be alt+shit+A
 */
 
/*
 * What is SQL?
 * 		- Structured Query Language
 *		- It is a language designed for manipulating relational database (tables)
 * What is a DBMS?
 * 		- Database Management System.
 * 		- We are using Microsoft SQL Server
 * 		- The flavor of SWL we are using is called tsql
 * 
 * There are 5 sublanguages of SQL: (Popular QC question)
 * 		- DDL
 * 			- Data Definition Language
 * 			- deals with manipulating the table structures
 * 			- keywords: create, alter, drop, truncate
 * 		- DML
 * 			- Data Manipulation Language
 * 			- deals with manipulating the records within the table
 * 			- keywords: insert, update, delete
 * 		- DQL
 * 			- Data Query Language
 * 			- deals with retrieving information from the database
 * 			- keyword: select
 * 		- DCL
 * 			- Data Control Language
 * 			- deals with granting and revoking access to database and schemas
 * 			- keywords: grant, revoke
 * 		- TCL
 * 			- Transaction Control Language
 * 			- deals with making official commits to the database
 * 			- commit, rollback, savepoint
 * 
 * 	What is a transaction?
 * 		- its an official commit to the database
 * 
 * 2 inserts 2 updates 4 deletes;
 * 
 * What are the properties of a transaction(Acid)? (Popular QC question)
 * 	- Atomicity: all or nothing... all operations will execute succesfully or none at all
 * 	- Consistency: Constraints will be followed, all constraints are enforced
 * 	- Isolation: Transactions cannot interfere with one another
 * 	- Durability: once a commit happens, that is the new state of the database
 */

/* DDL
 * 
 * What are the datatypes of sql?
 * 	- varchar(50): utilize for strings
 * 	- double precision: used for decimals
 * 	- money: used for money who would have guessed
 *  - date: provides a date 
 *  - bit: true/false
 * 
 * What is a constraint?
 * 	- rules a column must follow
 * 
 * What are some constraints we can use?
 * 	- unique: The value needs to be unique within the column
 * 	- not null: you must have a value for that specfic column
 * 	- default: if a value is not inserted, we can define a default value to be inputted
 * 
 * What is a primary key?
 *  - its a unique identifier for a record/row in a table
 * 	- implicitly unique and not null
 * There are 3 different types of primary key:
 * 	- natural key: unique identifier that is generated outside of the database
 * 		-examples: username, ssn, phone number, email
 * 	- surrogate keys: autogenerated from inside of the database
 * 		-there is a constraint called identity that generates a unique number
 *  - composite keys: 
 * 		- unique identifier from the combination of 2 or more columns
 * */
create table sublanguages.users(
	username varchar(50) unique not null,
	password varchar(50) not null,
	age int,--since i didn't add a constraint, this value can be null
	net_worth double precision not null,
	date_created date default getdate(),
	like_cilantro bit default 0, -- 0 is false, 1 is true
	primary key(username)
);

--The constraint is found by running the second command and copy-pasting the specified constraint in the error msg
alter table sublanguages.users drop constraint DF__users__like_cila__489AC854;
alter table sublanguages.users drop column like_cilantro;

-- we utilize the drop keyword to remove a table
drop table sublanguages.users;

--To view all of a table use the following command, you can replace the star with the name of a column as well to just see that column
select * from sublanguages.users;


/* DML
 * 	-Data Manipulation Language
 * 	-deals with manipulating the record of a table
 * 	-keywords: insert, update, delete
 * 
 */
 
--To create a new record must include the columns and values for a not null CONSTRAINT 
insert into sublanguages.users (username, password, net_worth) values('Jane123','pass123',200000.21);
--To update a record with information, need to specify record using where clause
update sublanguages.users set age = 98 where username='Jane123';
--To delete a record or set of records with specific constraints
delete from sublanguages.users where net_worth >100;

drop table sublanguages.posts;
create table sublanguages.posts(
	post_id int identity, --identity auto increments the value in a column ..used for surrogate key
	content varchar(255) not null,
	author_fk varchar(50) foreign key references sublanguages.users(username),
	primary key(post_id)
);

/*
 * What is multiplicity?
 * 	- the relationship between two tables
 * 	
 * 	- one to one
 * 	- one to many
 * 		- the "many table" has a foreign key to the primary key of the "one table"
 * 	- many to one
 *		 - the "many table" has a foreign key to the primary key of the "one table"
 *  - many to many
 * 		- you need to create an external table called a junction table
 * 
 * user, posts
 * 
 * What is a foreign key/
 * 	- a column that refernces another column
 * */
insert into sublanguages.posts (content, author_fk) values('This is my dope content', 'kev123');

select*from sublanguages.posts;

create table sublanguages.likes(
	post_fk int foreign key references sublanguages.posts(post_id),
	user_fk varchar(50) foreign key references sublanguages.users(username),
	primary key(post_fk,user_fk)
);
insert into sublanguages.posts (content, author_fk) values('This is a cool post 2', 'kev123');
insert into sublanguages.likes(post_fk,user_fk) values(1,'jane123');
select*from sublanguages.likes;